version: "3.4"

networks:  
  new-newxum-networking:

services:
  keycloak: 
    image: ${DOCKER_REGISTRY-}/new-nexum-keycloak:${TAG}
    container_name: new-nexum-keycloak
    build:
      context: "./keycloak"
      dockerfile: "./Dockerfile"
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/containers/identity:/opt/keycloak/data
      - ./keycloak/containers/.files:/opt/keycloak/data/import       
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost    
    restart: always      
    networks:
      - new-newxum-networking

  identity.api:
    image: ${DOCKER_REGISTRY-}/identity.api:${TAG}
    container_name: identity.api
    build: 
      context: "../backend/src"
      dockerfile: "./Services/Users/NewNexum.Users.Api/Dockerfile"
    ports:
      - "5002:5002"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5002;  

  profile.api:
    image: ${DOCKER_REGISTRY-}/profile.api:${TAG}
    container_name: profile.api
    build: 
      context: "../backend/src"
      dockerfile: "./Services/Profile/NewNexum.Profile.Api/Dockerfile"
    ports:
      - "7000:7000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:7000;            

