version: "3.4"

services:
  profile:
    image: ${REPOSITORY}/profile.api:${TAG}
    container_name: profile.api
    build: 
      context: "../backend/src"
      dockerfile: "./Services/Profile/NewNexum.Profile.Api/Dockerfile"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:7000;