apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-env-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings_ProfileDB: Data Source=.;Initial Catalog=Certification;Integrated Security=True;Encrypt=false;pooling=true
  ASPNETCORE_URLS: http://+:7000;      
  ASPNETCORE_HTTP_PORTS: "7000"