apiVersion: apps/v1
kind: Deployment
metadata: 
  name: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: profile
  template:
    metadata:
      labels:
        app.kubernetes.io/name: profile 
    spec:
      containers: 
      - name: profile
        image: gulhermepsantos/gulhermepsantos/profile.api:v1
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m" 
          limits:
            memory: "250Mi"
            cpu: "500m"
        ports:
        - containerPort: 7000
        envFrom:
        - configMapRef: 
            name: env-config
  

