import type { Metadata } from "next";

import { PropsWithChildren } from "react";
import { Roboto } from "next/font/google";
import { ThemeProviderNexum } from "@/providers/themeProviderNexum";

import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "nexus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="pt">
      <body className={roboto.className}>
        <ThemeProviderNexum attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProviderNexum>
      </body>
    </html>
  );
}
